name: Tests

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      # E2E tests running with Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run E2E Tests
        run: xvfb-run --auto-servernum -- pnpm test:e2e
        env:
          NODE_ENV: test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Stop Test Node
        run: pnpm node:dev stop --test --debug
