name: Tests

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Setup Docker
        uses: ./.github/actions/setup-docker
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Dependencies
        run: pnpm install
      
      - name: Start Test Node
        run: pnpm node:start

      # E2E tests running with Playwright
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run E2E Tests
        run: xvfb-run --auto-servernum -- pnpm test:all
        env:
          NODE_ENV: development

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: packages/app/playwright-report/
          retention-days: 30

      - name: Stop Test Node
        run: pnpm node:stop
